# Generated by Django 4.2.7 on 2024-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gitlab_username',
            field=models.CharField(default='0', max_length=255, unique=True),
        ),
    ]
