# Generated by Django 4.2.7 on 2024-04-23 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0005_alter_student_gitlab_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='access_token',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
