# Generated by Django 4.2.7 on 2024-05-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0006_remove_teacher_access_token_delete_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gitlab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
