# Generated by Django 4.2.7 on 2024-05-13 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0010_alter_student_gitlab_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(related_name='classroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
