# Generated by Django 4.2.7 on 2024-05-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0011_remove_classroom_teacher_classroom_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
