# Generated by Django 4.2.7 on 2024-05-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0012_rename_teacher_classroom_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teachers',
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
