# Generated by Django 4.2.7 on 2024-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab_classroom', '0014_alter_classroom_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='template_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
