# Generated by Django 5.0.3 on 2024-03-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
